# API config
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: af-api-secrets
  namespace: argoflow
stringData:
  AF_API_CONFIG_B64: {{ .Values.api.parameters.config64 }}
  AF_API_TOKEN: {{ .Values.smartlinkCreator.parameters.afApiToken }}
  KEEEX_PASSPHRASE: {{ .Values.smartlinkCreator.parameters.keeexPassphrase }}
  SMTP_PASS: {{ .Values.smartlinkCreator.parameters.smtpPassword }}
---
