# API config
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: af-api-secrets
  namespace: argoflow
stringData:
  AF_API_CONFIG_B64: {{ .Values.api.parameters.config64 }}
  AF_API_TOKEN: {{ .Values.smartlinkCreator.parameters.afApiToken }}
  KEEEX_PASSPHRASE: {{ .Values.smartlinkCreator.parameters.keeexPassphrase }}
  SMTP_PASS: {{ .Values.smartlinkCreator.parameters.smtpPassword }}

---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: sso-secret
  namespace: argoflow
stringData:
  JWT_SECRET: {{ .Values.sso.parameters.jwtSecret }}
  MASTER_PASSWORD: {{ .Values.sso.parameters.masterPassword }}
  MYSQL_LOGIN: {{ .Values.sso.parameters.mysqlLogin }}
  MYSQL_PASSWORD: {{ .Values.sso.parameters.mysqlPassword }}