apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: argoflow
spec:
  replicas: 1
  serviceName: mongo-service
  selector:
    matchLabels:
      component: mongo
  template:
    metadata:
      labels:
        component: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4.4
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-persistent-volume
          mountPath: /data/db
          subPath: mongo
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-volume
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 24Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: argoflow
spec:
  type: ClusterIP
  selector:
    component: mongo
  ports:
    - port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-compass
  namespace: argoflow
  annotations:
    # Add BAPI/WAPI Developers group
    service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: '{{ .Values.common.extraSecurityGroup }}'
spec:
  type: LoadBalancer
  selector:
    component: mongo
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  - name: metrics
    port: 9216
    targetPort: 9216
  # By default AWS ELB is open for ALL IPs (0.0.0.0/0)!!! So we use our VPC CIDR
  loadBalancerSourceRanges:
    - "{{ .Values.common.loadBalancerSourceRanges }}"