apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.api.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: {{ .Values.api.name }}
        cluster: {{ .Values.labels.cluster }}
      annotations:
        timestamp: "{{ date "20060102-150405" .Release.Time }}"
    spec:
      containers:
      - name: {{ .Values.api.name }}
        image: {{ .Values.api.image.repository }}:{{ .Values.api.version }}
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        # command: ["npm"]
        # args: []
        volumeMounts:
        - name: efs
          mountPath: {{ .Values.storage.mountPath }}
        env:
        - name: NODE_ENV
          value: {{ .Values.api.parameters.nodeEnv }}
        - name: AF_API_CONFIG_B64
          valueFrom:
            secretKeyRef:
              name: af-api-secrets
              key: AF_API_CONFIG_B64
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: efs
        persistentVolumeClaim:
          claimName: efs-claim

---
apiVersion: v1
kind: Service
metadata:
  name: api-internal-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 8181
    targetPort: 80
  selector:
    name: {{ .Values.api.name }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: api-internal-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.org/client-max-body-size: "100m"
    nginx.ingress.kubernetes.io/enable-cors: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.api.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: api-internal-service
                port:
                  number: 8181