apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse-bulk
  namespace: argoflow
spec:
  replicas: 1
  serviceName: clickhouse-bulk-service
  selector:
    matchLabels:
      component: clickhouse-bulk
  template:
    metadata:
      labels:
        component: clickhouse-bulk
    spec:
      containers:
      - name: clickhouse-bulk
        image: nikepan/clickhouse-bulk:1.3.7
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: tcp
          containerPort: 8124
        env:
        - name: CLICKHOUSE_SERVERS
          value: "http://clickhouse-service:8123"
        - name: CLICKHOUSE_FLUSH_COUNT
          value: "10000"
        - name: CLICKHOUSE_FLUSH_INTERVAL
          value: "1000"
        - name: DUMP_CHECK_INTERVAL
          value: "300"
        - name: CLICKHOUSE_DOWN_TIMEOUT
          value: "60"
        - name: CLICKHOUSE_CONNECT_TIMEOUT
          value: "10"

---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-bulk-service
  namespace: argoflow
spec:
  type: LoadBalancer
  selector:
    component: clickhouse-bulk
  ports:
    - name: tcp
      port: 8124
      targetPort: 8124


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-proxy
  namespace: argoflow
spec:
  selector:
    matchLabels:
      component: clickhouse-proxy
  replicas: 1
  template:
    metadata:
      labels:
        component: clickhouse-proxy
    spec:
      containers:
      - name: clickhouse-proxy
        image: argoteam/clickhouse-proxy:dev
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: tcp
          containerPort: 80
        - name: udp
          containerPort: 8091
        env:
        - name: CLICKHOUSE_INGESTOR
          value: "http://clickhouse-bulk-service:8124"

---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-proxy-service
  namespace: argoflow
spec:
  type: LoadBalancer
  selector:
    component: clickhouse-proxy
  ports:
    - name: tcp
      port: 80
      targetPort: 80
    - name: udp
      port: 8091
      targetPort: 8091


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: argoflow
spec:
  replicas: 1
  serviceName: clickhouse-service
  selector:
    matchLabels:
      component: clickhouse
  template:
    metadata:
      labels:
        component: clickhouse
    spec:
    #   initContainers:
    #   # To increase the ulimit
    #   - name: increase-the-ulimit
    #     image: busybox
    #     command:
    #     - sh
    #     - -c
    #     - ulimit -n 262144
    #     securityContext:
    #       privileged: true
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:22.9.3
        ports:
        - containerPort: 8123
        - containerPort: 9000
        volumeMounts:
        - name: clickhouse-persistent-volume
          mountPath: /var/lib/clickhouse
          subPath: clickhouse
  volumeClaimTemplates:
  - metadata:
      name: clickhouse-persistent-volume
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 512Gi

---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
  namespace: argoflow
spec:
  type: ClusterIP
  selector:
    component: clickhouse
  ports:
    - name: external
      port: 8123
      targetPort: 8123
    - name: internal
      port: 9000
      targetPort: 9000
